Ejercicio 1. Crea un notebook de jupyter denominado
Tarea11.ipynb y a continuación crea un vector fila que contenga
los numeros enteros del 20 al 30.

In [5]:
import numpy as np

fila = np.array(range(20,31))
print(fila)

[20 21 22 23 24 25 26 27 28 29 30]


Ejercicio 2. Crea otro array seleccionando los 6 primeros
elementos del array que has creado en el ejercicio anterior.

In [9]:
fila_reducido = np.array(fila[0:7])
fila_reducido

array([20, 21, 22, 23, 24, 25, 26])

Ejercicio 3. Crea un vector fila llamado Ejer3a con los números
enteros del 100 al 200. Cuando lo hayas hecho crea un nuevo
vector denominado Ejer3b que contenga las 10 primeras
posiciones de Ejer3a

In [48]:
Ejer3a = np.array(range(100,201))
Ejer3b = np.array(Ejer3a[:10]).copy()

print(Ejer3a)
print(Ejer3b)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]
[100 101 102 103 104 105 106 107 108 109]


Ejercicio 4. En el array resultado del ejercicio 3 (Ejer3b) haz que
en las posiciones pares el valor sea 9999. Comprueba el valor
del array Ejer3a. Cómo explicas el resultado al visualizar Ejer3a?.
Cómo lo resolverías?

In [44]:
indices_pares = np.arange(len(Ejer3b)) % 2 == 0

Ejer3b[indices_pares] = 9999

print(Ejer3b)
type(Ejer3b)

[9999  101 9999  103 9999  105 9999  107 9999  109]


numpy.ndarray

In [54]:
Ejer3x = np.where(np.arange(len(Ejer3b)) % 2 == 0, 9999, Ejer3a[:10])

print(Ejer3x)
type(Ejer3x)

[9999  101 9999  103 9999  105 9999  107 9999  109]


numpy.ndarray

Ejercicio 5. Crea un array 3x3 denominado Ejer5a que contenga
los números enteros del 9 al 1 dispuestos en filas. Crea un un
array denominado Ejer5b que contenga las 2 primeras filas de
Ejer5a. Crea un un array denominado Ejer5c que contenga las 2
primeras columnas de Ejer5a. Crea un un array denominado
Ejer5c que contenga la submatriz 2x2 de la parte inferior
izquierda de Ejer5a

In [37]:
Ejer5a = np.arange(9, 0, -1).reshape(3,3)

# Ejer5a = np.arange(9, 0, -1)
# Ejer5a = Ejer5a.reshape(len(Ejer5a),1)

Ejer5b = Ejer5a[:2]
Ejer5c = Ejer5a[:,:2]
Ejer5d = Ejer5a[1:,:2]


print(Ejer5a)
print(Ejer5b)
print(Ejer5c)
print(Ejer5d)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]]
[[9 8]
 [6 5]
 [3 2]]
[[6 5]
 [3 2]]
