Crea una matriz denominada
Ejer3 de tamaño 50x50 cuyos elementos
constituyan una distribución normal aleatoria de media 0 y desviación típica
unidad

In [3]:
from numpy import random

Ejer3 = random.randn(50,50)

print(Ejer3)

(50, 50)


A partir de la matriz Ejer3, calcula: <br>
•
La media de los elementos de la matriz<br>
•
La desviación típica de los elementos de la matriz<br>
•
La media de los elementos de cada fila de la matriz.<br>
•
La desviación típica de los elementos de cada fila de la matriz.<br>
•
La suma de los elementos de cada fila de la matriz.<br>
•
La suma de los elementos de cada columna de la matriz

In [15]:
media = Ejer3.mean()
desv_tip = Ejer3.std()
media_filas = Ejer3.mean(axis=1)
desv_tip_filas = Ejer3.std(axis = 1)
suma_filas = Ejer3.sum(axis = 1)
suma_columnas = Ejer3.sum(axis = 0)


print(media)
print(desv_tip)
print(len(media_filas))
print(suma_filas[0], Ejer3[0].sum())
print(suma_columnas[0], Ejer3[:,0].sum())


-0.015725586246502887
1.0053917445182312
50
6.683835794785301 6.683835794785301
-5.935913925815772 -5.935913925815772


In [25]:
import numpy as np

matriz = np.array([[[1,2,3],
                    [4,5,6]],
                    
                    [[7,8,9],
                     [10,11,12]]])

matriz = matriz.transpose(2,0,1)
print(matriz)

[[[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8 11]]

 [[ 3  6]
  [ 9 12]]]


Guarda el array anterior en un fichero explorando las diferentes opciones de
almacenar arrays

Intenta cargar algunos de los ficheros almacenados