![IDAL](https://i.imgur.com/tIKXIG1.jpg)  

#**Máster en Inteligencia Artificial Avanzada y Aplicada:  IA^3**
---


# PyTorch Basico Ejercicios

En estos ejercicos crearemos algunos tensores y realizaremos operaciones básicos sobre ellos.


### 1. Realiza las importaciones standard
Importa torch and NumPy

In [55]:
# TU CÓDIGO AQUÍ
import torch
import numpy as np


### 2. Configura una semilla para los generadores de ambos Numpy y Pytorch con el valor "42"
Esto permite reproducir los mismos resultados "aleatorios"

In [56]:
# TU CÓDIGO AQUÍ

np.random.seed(42)
torch.manual_seed(42)

### 3. Crea un NumPy array llamado "arr" que contenga 6 enteros aleatorios entre 0 (incluido) y 5 (excluido)

In [57]:
# TU CÓDIGO AQUÍ

arr = np.random.randint(0, 5, 6)
arr

array([3, 4, 2, 4, 4, 1])

In [58]:
# No escribas aquí. Compara tu resultado con lo que se muestra:
arr

array([3, 4, 2, 4, 4, 1])

### 4. Crea a tensor "x" del array anterior

In [59]:
# TU CÓDIGO AQUÍ

x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1])

### 5. Cambia el tipo de dato (`dtype`) de x de 'int32' a 'int64'
Nota: 'int64' tambien se puede llamar 'LongTensor'

In [60]:
# TU CÓDIGO AQUÍ
x = x.type(torch.int64)
x.type()

'torch.LongTensor'

### 6. Cambia la forma del tensor a un 3x2 tensor
Hay varias formas de hacer esto

In [61]:
# TU CÓDIGO AQUÍ
x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [62]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

### 7. Retorna la columna de la derecha del tensor x

Atención a la forma de hacerlo. Hay varias posibilidades y cada una entrega los datos de forma diferente

In [63]:
# # TU CÓDIGO AQUÍ
x[:,1:]

tensor([[4],
        [4],
        [1]])

In [64]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

In [65]:
# TU CÓDIGO AQUÍ
x[:,1]

tensor([4, 4, 1])

In [66]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

### 8. Sin cambiar x, retorna un tensor con los valores cuadradaticos de x
Hay varias formas de hacer esto

In [67]:
# TU CÓDIGO AQUÍ
x.pow(2)



tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [68]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

### 9. Crea un tensor "y" con el mismo número de elementos que x, de forma que pueda realizar una multiplicación de matrices.

Utiliza funciones de Pytorch directamente para crear un tensor de enteros aleatorios entre 0 (incluido) y 5 (excluido).

Ten en cuenta qué forma debe tener para hacer la multiplicación de matrices...

In [69]:
# TU CÓDIGO AQUÍ

y = torch.randint_like(x, 0, 5).transpose(0,1)
y


tensor([[2, 1, 1],
        [2, 4, 0]])

In [70]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

### 10. Realiza el producto de matrices entre x e y

In [71]:
# TU CÓDIGO AQUÍ
x.mm(y)


tensor([[14, 19,  3],
        [12, 18,  2],
        [10,  8,  4]])

In [72]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

## Enhorabuena! Vamos calentando motores...

## Fin del Notebook

Referencias y modelos empleados para el Notebook:

*   Documentación de [Pytorch](https://pytorch.org/docs/stable/index.html)
*   [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi
*   [FastAI](https://www.fast.ai/) development notebooks by Jeremy Howard.
*   Documentación y cursos en [Pierian Data](https://www.pieriandata.com/)
